name: Deploy Astro App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-astro.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm install

      - name: Build Astro app (frontend)
        working-directory: ./frontend
        run: npm run build

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Deploy to GitHub Pages
        run: rsync -avz --delete ./frontend/dist/* https://lbsa71:${{ secrets.GH_PAGES_DEPLOY_TOKEN }}@github.com/lbsa71/lbsa71.github.io/
