name: Deploy Astro App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-astro.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm install

      - name: Build Astro app (frontend)
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git clone https://${secrets.GH_PAGES_DEPLOY_TOKEN}@github.com/lbsa71/lbsa71.github.io.git --branch=master gh-pages
          rm -rf gh-pages/linkedin-cv-export/*
          cp -r frontend/dist/. gh-pages/linkedin-cv-export/
          cd gh-pages
          git add .
          git commit -m "Deploy new build"
          git push origin master
